### ISSUE TITLE
Passing a --something_that_is_not_a_command won't cause a failure in biox

### ISSUE THREAD

**Issue by nizardrou** [biosails/BioX-Workflow-Command#3]
Inadvertently, I was trying to --select_rules create_analysis_dirs, but instead I typed --create_analysis_dirs. This still created a workflow that was then submitted using hpcrunner resulting in the below,
```
[2017/04/27` 10:14:04] Here is your tabular dependency list in alphabetical order 
.-------------------.
| JobName    | Deps |
+------------+------+
| hpcjob_001 |      |
`'------------+------'

```
Wouldn't be better if unrecognized biox flags like the one above cause and exception (error: unrecognized argument --create_analysis_dirs)?

**Comment by jerowe** [comment]
Thanks for the bug report. This is fixed in the new release.
