### ISSUE TITLE
Strange sample ".biosails" when running biox

### ISSUE THREAD

**Issue by nizardrou** [biosails/BioX-Workflow-Command#30]
When running the following command,
`biox run -w fastqc.yml -o NCB-234-QC.sh`
in the following directory,
`/scratch/cz21/Chip_seq_Mouse/`

The resulting workflow finds a sample called .biosails, and creates all data/processed relevant directories,
`[2017/09/18 11:10:25] Found samples: .biosails, Sample_Input, Sample_KOB-H2AZ, Sample_KOB-H3K27me3, Sample_KOB-H3K4me3, Sample_WTB-H2AZ, Sample_WTB-H3K27me3, Sample_WTB-H3K4me3
`

This is the sample rule in my YML conf,
`    - file_rule: (Sample.*)$
`

This job will obviously fail, but only affecting the .biosails sample, still it seems that this shouldn't be matched according to the file rule.

**Comment by jerowe** [comment]
The new variable to declare the sample regexp is `sample_rule`, but it should be backwards compatible to `file_rule`, so this is still a bug.

I updated that workflow to use `sample_rule`, and it works as expected.
